apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkin
  namespace: uhc-core
spec:
  replicas: 1
  selector:
    matchLabels: { app: checkin }
  template:
    metadata:
      labels: { app: checkin }
    spec:
      containers:
        - name: checkin
          image: acruhcdev.azurecr.io/checkin:0.1
          ports: [{ containerPort: 80 }]
          readinessProbe:
            httpGet: { path: "/healthz", port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/healthz", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "250m", memory: "128Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: checkin
  namespace: uhc-core
spec:
  selector: { app: checkin }
  ports: [{ port: 80, targetPort: 80 }]
  type: ClusterIP