apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uhc-core
  namespace: uhc-core
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts: [api.urbanhealth.club]
      secretName: uhc-core-tls
  rules:
    - host: api.urbanhealth.club
      http:
        paths:
          - path: /v1/memberships
            pathType: Prefix
            backend:
              service:
                name: membership
                port: { number: 80 }
          - path: /v1/bookings
            pathType: Prefix
            backend:
              service:
                name: booking
                port: { number: 80 }
          - path: /v1/checkins
            pathType: Prefix
            backend:
              service:
                name: checkin
                port: { number: 80 }
