apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uhc-core

resources:
  - namespace.yaml
  - deployment-membership.yaml
  - deployment-booking.yaml
  - deployment-checkin.yaml
  - ingress.yaml
